const addNumber = () => {
    console.log(2 + 4);
};

addNumber();

const throwNewError = () => {
    throw new Error("Your program terminated because of error");
};

throwNewError();